title: zyfeng
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Real Researcher
baseurl: "" # the subpath of your site, e.g. /blog
theme: jekyll-theme-architect # my theme
url: "https://zyfeng-go.github.io/" # the base hostname & protocol for your site
permalink: /:title/
excerpt_separator: <!--end_excerpt-->

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  episodes:
    output: true
  seasons:
    output: true
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "seasons"
    values:
      layout: "season"
